---
- name: Create systemd for traefik
  template:
    src: "{{ traefik_systemd_unit_template }}.j2"
    dest: "{{ traefik_systemd_unit_dest }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart traefik service

- name:  Install traefik and create config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_install_dir }}"

- name: Copy config file
  template:
    src: "{{ traefik_template }}.j2"
    dest: "{{ traefik_config_file }}"
    owner: root
    group: root
    mode: 0744
  notify:
    - Restart traefik service

- name: Check if traefik service is stopped before update
  service:
    name: traefik
    state: stopped
    enabled: yes
  when: traefik_update == "yes"

- name: Download Traefik
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
    force: "{{ traefik_update }}"
  with_items:
    - url: "{{ traefik_binary_url }}"
      dest: "{{ traefik_bin_path }}"

- name: Ensure traefik service is enabled and running
  systemd:
    name: traefik
    state: started
    enabled: yes
    daemon_reload: yes